DSG-623/Set-spring-profile-dynamically
Nuvalence/dsgov-audit-service pull request #48
Opened 2023-05-18 16:23 UTC by afcalderonm

## Description

configure spring profile to be set dynamically

[___JIRA_TICKET_TITLE___](//jira_url)

## Motivation and Context

We recently created the dsgov-logging lib which has the configuration files:

logback-local.xml

logback-cloud.xml

From this it was decided that we will only use 2 spring profiles, local and cloud, but this affected some apps for cloud deployment, more specifically in dev env.

## Areas for Focus

## How Has This Been Tested?

tested locally and saw that the active profile was local after the adjustment, it was default before.

## Screenshots (if appropriate):

## Types of changes

Patch

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
  Minor
- [ ] New feature (non-breaking change which adds functionality)
  Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met.

2023-05-18 16:46 UTC, jgnuvalence commented on skaffold.yaml
please add:

`googleCloudBuild:`
`        projectId: dsgov-services`
`        gradleImage: gradle:7.6-jdk11-alpine`

in profiles.build

2023-05-18 16:52 UTC, jgnuvalence commented on skaffold.yaml
after doing this we have to change the profiles.deploy.setValueTemplates with:

`image.repository: "{{.IMAGE_REPO_us_east4_docker_pkg_dev_dsgov_services_application_dsgov_work_manager}}"`
            
`image.tag: "{{.IMAGE_TAG_us_east4_docker_pkg_dev_dsgov_services_application_dsgov_work_manager}}@{{.IMAGE_DIGEST_us_east4_docker_pkg_dev_dsgov_services_application_dsgov_work_manager}}"`

2023-05-18 16:55 UTC, jgnuvalence commented
I leave the comments of the things I see that are missing, but I would really like @dtsong  to review as well

2023-05-18 18:42 UTC, jgnuvalence commented
@afcalderonm please also see the changes done in this [PR](https://github.com/Nuvalence/dsgov-work-manager/pull/71/files) for `.ci/cloudbuild-push-request.yaml`
and for `service/build.gradle` note that the jib configurations was removed, you need to do the same, after that you need to check that the spring profile es set correctly in minikube when you deploy

2023-05-18 19:15 UTC, jgnuvalence approved these changes
LGTM

2023-05-19 13:39 UTC, dtsong commented on skaffold.yaml
> +            image.tag: "{{.IMAGE_TAG_us_east4_docker_pkg_dev_dsgov_services_application_dsgov-audit-service}}@{{.IMAGE_DIGEST_us_east4_docker_pkg_dev_dsgov_services_application_dsgov-audit-service}}"
We will want all of these to have underscores like so:

```
IMAGE_REPO_us_east4_docker_pkg_dev_dsgov_services_application_dsgov_audit_service
IMAGE_TAG_us_east4_docker_pkg_dev_dsgov_services_application_dsgov_audit_service
IMAGE_DIGEST_us_east4_docker_pkg_dev_dsgov_services_application_dsgov_audit_service
```

2023-05-19 13:40 UTC, dtsong requested changes
One comment, otherwise looks good!

2023-05-19 13:59 UTC, dtsong approved these changes

2023-05-19 14:00 UTC, merged